(()=>{
const E=window.UTEngine,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],canvas=$('#galaxy'),ctx=canvas.getContext('2d');
let world,paused=false,speed=1,overlay='political',selectedSystem=null,selectedFaction=null,ledger='factions',timelineCutoff=0,last=performance.now(),acc=0,cam={scale:1,ox:0,oy:0},drag=null;
const fmt=n=>n>=1000?`${(n/1000).toFixed(1)}k`:n.toFixed(n<10?1:0), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function boot(){world=E.generate($('#seedInput').value,{systemCount:180,factionCount:10,temperament:'balanced'});$('#modalSeed').value=world.seed;bind();refreshAll();requestAnimationFrame(loop)}
function loop(t){const dt=Math.min(.25,(t-last)/1000);last=t;if(!paused){acc+=dt*speed;let steps=0;while(acc>=1&&steps<20){E.stepMonth(world);acc-=1;steps++}if(steps)refreshAll()}draw();requestAnimationFrame(loop)}
function refreshAll(){renderMetrics();renderTimeline();renderLedger();renderFocus();renderLegend();$('#yearLabel').textContent=`${world.year}.${String(world.month).padStart(2,'0')}`}
function renderMetrics(){const s=E.summary(world),er=E.era(world);$('#metricFactions').textContent=s.factions;$('#metricPopulation').textContent=`${fmt(s.population)} B`;$('#metricWars').textContent=s.wars;$('#metricTrade').textContent=fmt(s.trade);$('#eraName').textContent=er[0];$('#eraText').textContent=er[1]}
function eventIcon(t){return{war:'⚔',diplomacy:'◇',economy:'¤',politics:'⚑',science:'⌁',crisis:'☄'}[t]||'•'}
function renderTimeline(){const filter=$('#eventFilter').value;const ev=world.events.filter(e=>e.id>timelineCutoff&&(filter==='all'||e.type===filter)).slice(0,120);$('#timeline').innerHTML=ev.length?ev.map(e=>`<article class="event e-${e.type} importance-${e.importance}"><div class="event-date">${e.stamp}</div><div class="event-icon">${eventIcon(e.type)}</div><div><h3>${esc(e.title)}</h3><p>${esc(e.text)}</p></div></article>`).join(''):'<div class="empty-list">No events match this view yet.</div>'}
function renderLedger(){const el=$('#ledgerContent');if(ledger==='factions'){const fs=[...world.factions].filter(f=>f.alive).sort((a,b)=>E.strength(world,b.id)-E.strength(world,a.id));el.innerHTML=`<div class="faction-table"><div class="table-row head"><span>Power</span><span>Faction</span><span>Systems</span><span>Fleet</span><span>Stability</span><span>Tech</span></div>${fs.map((f,i)=>`<button class="table-row faction-row" data-faction="${f.id}"><span class="rank">#${i+1}</span><span class="faction-name"><i style="background:${f.color}"></i><b>${esc(f.name)}</b><small>${esc(f.government)} · ${esc(f.trait)}</small></span><span>${E.ownerSystems(world,f.id).length}</span><span>${fmt(f.fleet)}</span><span>${Math.round(f.stability)}%</span><span>${f.tech.toFixed(2)}</span></button>`).join('')}</div>`;$$('[data-faction]').forEach(b=>b.onclick=()=>selectFaction(+b.dataset.faction))}
else if(ledger==='wars'){const ws=world.wars.filter(w=>w.active);el.innerHTML=ws.length?`<div class="card-grid">${ws.map(w=>{const a=E.getFaction(world,w.a),b=E.getFaction(world,w.b);return`<div class="ledger-card war-card"><span>ACTIVE WAR · ${w.months} MONTHS</span><h3>${esc(a?.name)} <em>vs</em> ${esc(b?.name)}</h3><p>${esc(w.reason)} · ${w.battles} battles · ${w.conquests} systems captured</p><div class="war-score"><b style="color:${a?.color}">${w.aScore}</b><i></i><b style="color:${b?.color}">${w.bScore}</b></div></div>`}).join('')}</div>`:'<div class="empty-list">The galaxy is currently at peace.</div>'}
else if(ledger==='alliances'){const as=world.alliances.filter(a=>a.active);el.innerHTML=as.length?`<div class="card-grid">${as.map(a=>`<div class="ledger-card"><span>ALLIANCE · SINCE ${Math.floor(a.formed)}</span><h3>${esc(a.name)}</h3><p>${a.members.map(id=>esc(E.getFaction(world,id)?.name)).join(' + ')}</p></div>`).join('')}</div>`:'<div class="empty-list">No active alliances.</div>'}
else{const s=E.summary(world),hist=world.statsHistory.slice(-60),max=Math.max(1,...hist.map(x=>x.population));el.innerHTML=`<div class="stats-ledger"><div class="big-stat"><span>COLONIZED</span><b>${s.colonized}/${world.systems.length}</b></div><div class="big-stat"><span>GALACTIC ECONOMY</span><b>${fmt(s.economy)}</b></div><div class="big-stat"><span>RECORDED EVENTS</span><b>${world.events.length}</b></div><div class="big-stat"><span>EXTINCT FACTIONS</span><b>${world.factions.filter(f=>!f.alive).length}</b></div></div><div class="history-chart"><span>POPULATION HISTORY</span><div>${hist.map(h=>`<i style="height:${Math.max(3,h.population/max*100)}%" title="${h.year}: ${h.population.toFixed(1)}B"></i>`).join('')}</div></div>`}}
function selectFaction(id){selectedFaction=id;selectedSystem=E.getFaction(world,id)?.capital??null;renderFocus();draw()}
function renderFocus(){const panel=$('#focusBody'),title=$('#focusTitle'),dot=$('#focusDot');if(selectedSystem!=null){const s=world.systems[selectedSystem],f=s.owner==null?null:E.getFaction(world,s.owner);title.textContent=s.name;dot.style.background=f?.color||'#647786';selectedFaction=f?.id??null;panel.className='';panel.innerHTML=`<div class="focus-owner">${f?`<i style="background:${f.color}"></i><button data-focus-faction="${f.id}">${esc(f.name)}</button>`:'<span>Unclaimed system</span>'}</div><div class="focus-stats"><div><span>STAR</span><b>${s.star}-class</b></div><div><span>POPULATION</span><b>${s.owner==null?'—':fmt(s.population)+' B'}</b></div><div><span>ECONOMY</span><b>${s.owner==null?'—':fmt(s.economy)}</b></div><div><span>DEFENSE</span><b>${Math.round(s.defense)}</b></div><div><span>HABITABILITY</span><b>${s.habitability}%</b></div><div><span>RESOURCES</span><b>${s.resources}%</b></div></div>${s.capital?'<div class="tag capital-tag">◆ FACTION CAPITAL</div>':''}${s.owner!=null?`<div class="meter-row"><span>Unrest</span><div><i style="width:${clamp(s.unrest,0,100)}%"></i></div><b>${Math.round(s.unrest)}%</b></div>`:''}`;panel.querySelector('[data-focus-faction]')?.addEventListener('click',e=>showFaction(+e.currentTarget.dataset.focusFaction));return}
if(selectedFaction!=null){showFaction(selectedFaction);return}title.textContent='No system selected';dot.style.background='#4b5e6d';panel.className='focus-empty';panel.textContent='Select a star system or a faction from the ledger.'}
function showFaction(id){const f=E.getFaction(world,id);if(!f)return;selectedFaction=id;selectedSystem=null;$('#focusTitle').textContent=f.name;$('#focusDot').style.background=f.color;const ss=E.ownerSystems(world,id),wars=world.wars.filter(w=>w.active&&(w.a===id||w.b===id)),friends=E.aliveFactions(world).filter(x=>x.id!==id).sort((a,b)=>E.relation(world,id,b.id)-E.relation(world,id,a.id));$('#focusBody').className='';$('#focusBody').innerHTML=`<div class="faction-banner" style="--f:${f.color}"><span>${esc(f.government)}</span><b>${esc(f.trait)}</b></div><div class="focus-stats"><div><span>SYSTEMS</span><b>${ss.length}</b></div><div><span>POPULATION</span><b>${fmt(ss.reduce((z,s)=>z+s.population,0))} B</b></div><div><span>FLEET</span><b>${fmt(f.fleet)}</b></div><div><span>TREASURY</span><b>${fmt(f.treasury)}</b></div><div><span>TECH</span><b>${f.tech.toFixed(2)}</b></div><div><span>STABILITY</span><b>${Math.round(f.stability)}%</b></div></div><div class="focus-lines"><p><span>Wars</span><b>${wars.length}</b></p><p><span>Record</span><b>${f.warsWon}W / ${f.warsLost}L</b></p><p><span>Prestige</span><b>${Math.round(f.prestige)}</b></p></div>${friends.length?`<div class="relations"><span>RELATIONSHIPS</span>${friends.slice(0,4).map(o=>{const r=E.relation(world,id,o.id);return`<button data-rel-faction="${o.id}"><i style="background:${o.color}"></i><b>${esc(o.name)}</b><em class="${r>25?'good':r<-25?'bad':''}">${Math.round(r)}</em></button>`}).join('')}</div>`:''}`;$$('[data-rel-faction]').forEach(b=>b.onclick=()=>selectFaction(+b.dataset.relFaction))}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function colorForSystem(s){if(overlay==='political')return s.owner==null?'#536474':E.getFaction(world,s.owner)?.color||'#777';if(overlay==='economy'){const v=clamp(s.economy/150,0,1);return `hsl(${190-v*135} 80% ${35+v*25}%)`}if(overlay==='population'){const v=clamp(s.population/12,0,1);return `hsl(${275-v*230} 78% ${35+v*28}%)`}return s.owner==null?'#56616d':E.getFaction(world,s.owner)?.color||'#777'}
function pos(s){return{x:(s.x*canvas.width)*cam.scale+cam.ox,y:(s.y*canvas.height)*cam.scale+cam.oy}}
function draw(){ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);const g=ctx.createRadialGradient(canvas.width*.52,canvas.height*.48,20,canvas.width*.5,canvas.height*.5,canvas.width*.7);g.addColorStop(0,'#121b2a');g.addColorStop(.45,'#0a101a');g.addColorStop(1,'#04070c');ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height);
ctx.lineWidth=1;ctx.globalAlpha=.18;ctx.strokeStyle='#60788d';for(const s of world.systems){const a=pos(s);for(const n of s.neighbors){if(n<s.id)continue;const b=pos(world.systems[n]);if(a.x<-20||a.x>canvas.width+20||a.y<-20||a.y>canvas.height+20)continue;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}
ctx.globalAlpha=.32;ctx.lineWidth=2;if(overlay==='political'||overlay==='diplomacy')for(const r of world.tradeRoutes){const af=E.getFaction(world,r.a),bf=E.getFaction(world,r.b);if(!af||!bf)continue;const a=pos(world.systems[af.capital]),b=pos(world.systems[bf.capital]);ctx.strokeStyle='#53e0b4';ctx.setLineDash([8,9]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}ctx.setLineDash([]);
if(overlay==='diplomacy'&&selectedFaction!=null){const a=E.getFaction(world,selectedFaction);if(a?.alive){const ap=pos(world.systems[a.capital]);for(const b of E.aliveFactions(world)){if(b.id===a.id)continue;const bp=pos(world.systems[b.capital]),r=E.relation(world,a.id,b.id);ctx.globalAlpha=.45;ctx.lineWidth=3;ctx.strokeStyle=E.atWar(world,a.id,b.id)?'#ff4d5e':E.allied(world,a.id,b.id)?'#58e8a7':r>0?'#6dbfff':'#ff9b6d';ctx.beginPath();ctx.moveTo(ap.x,ap.y);ctx.lineTo(bp.x,bp.y);ctx.stroke()}}}
ctx.globalAlpha=1;for(const s of world.systems){const p=pos(s);if(p.x<-20||p.x>canvas.width+20||p.y<-20||p.y>canvas.height+20)continue;let r=3.6*cam.scale;if(overlay==='economy')r+=(Math.min(120,s.economy)/120)*7*cam.scale;if(overlay==='population')r+=(Math.min(12,s.population)/12)*8*cam.scale;r=clamp(r,2.2,14);ctx.fillStyle=colorForSystem(s);ctx.shadowColor=colorForSystem(s);ctx.shadowBlur=s.capital?12:5;ctx.beginPath();ctx.arc(p.x,p.y,s.capital?r*1.6:r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(s.capital){ctx.strokeStyle='#fff';ctx.globalAlpha=.8;ctx.lineWidth=1.3;ctx.beginPath();ctx.arc(p.x,p.y,r*2.2,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}if(s.id===selectedSystem){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,r+8,0,Math.PI*2);ctx.stroke()}if(cam.scale>1.35&&(s.capital||s.id===selectedSystem)){ctx.font='600 14px system-ui';ctx.fillStyle='#e9f4ff';ctx.fillText(s.name,p.x+10,p.y-8)}}}
function renderLegend(){if(overlay==='political')$('#mapLegend').innerHTML=E.aliveFactions(world).slice(0,10).map(f=>`<button data-legend="${f.id}"><i style="background:${f.color}"></i>${esc(f.short)}</button>`).join('');else $('#mapLegend').innerHTML=`<span>${overlay==='economy'?'Low output → High output':overlay==='population'?'Sparse → Dense':'Select a faction to inspect relations'}</span>`;$$('[data-legend]').forEach(b=>b.onclick=()=>selectFaction(+b.dataset.legend))}
function findSystemAt(clientX,clientY){const r=canvas.getBoundingClientRect(),x=(clientX-r.left)*canvas.width/r.width,y=(clientY-r.top)*canvas.height/r.height;let best=null,bd=18;for(const s of world.systems){const p=pos(s),dd=Math.hypot(p.x-x,p.y-y);if(dd<bd){best=s;bd=dd}}return best}
function fit(){cam={scale:1,ox:0,oy:0}}
function zoom(f,cx=canvas.width/2,cy=canvas.height/2){const old=cam.scale,ns=clamp(old*f,.65,4);cam.ox=cx-(cx-cam.ox)*(ns/old);cam.oy=cy-(cy-cam.oy)*(ns/old);cam.scale=ns}
function save(){localStorage.setItem('ut-save',E.serialize(world));toast('Universe saved locally.')}function load(){try{const s=localStorage.getItem('ut-save');if(!s)return toast('No local save found.');world=E.deserialize(s);selectedSystem=selectedFaction=null;refreshAll();toast('Save loaded.')}catch(e){toast('Could not load save.')}}
function exportWorld(){const b=new Blob([JSON.stringify(world,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`universe-${world.seed}-${world.year}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function bind(){$$('.speed-btn').forEach(b=>b.onclick=()=>{speed=+b.dataset.speed;paused=false;$$('.speed-btn').forEach(x=>x.classList.toggle('active',x===b));$('#pauseBtn').textContent='❚❚'});$('#pauseBtn').onclick=()=>{paused=!paused;$('#pauseBtn').textContent=paused?'▶':'❚❚'};$$('.overlay-btn').forEach(b=>b.onclick=()=>{overlay=b.dataset.overlay;$$('.overlay-btn').forEach(x=>x.classList.toggle('active',x===b));renderLegend();draw()});$('#zoomInBtn').onclick=()=>zoom(1.25);$('#zoomOutBtn').onclick=()=>zoom(.8);$('#fitBtn').onclick=fit;$('#eventFilter').onchange=renderTimeline;$('#clearTimelineBtn').onclick=()=>{timelineCutoff=world.eventSeq;renderTimeline()};$$('#ledgerTabs button').forEach(b=>b.onclick=()=>{ledger=b.dataset.ledger;$$('#ledgerTabs button').forEach(x=>x.classList.toggle('active',x===b));renderLedger()});$('#saveBtn').onclick=save;$('#loadBtn').onclick=load;$('#exportBtn').onclick=exportWorld;$('#importInput').onchange=async e=>{try{world=E.deserialize(await e.target.files[0].text());selectedSystem=selectedFaction=null;refreshAll();toast('Universe imported.')}catch{toast('Invalid universe file.')}};$('#newUniverseBtn').onclick=()=>$('#newUniverseModal').classList.remove('hidden');$('#applySeedBtn').onclick=()=>{world=E.generate($('#seedInput').value,{systemCount:world.settings.systemCount,factionCount:world.settings.factionCount,temperament:world.settings.temperament});fit();refreshAll()};$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));$('#createUniverseBtn').onclick=()=>{const seed=$('#modalSeed').value||'SOL-2200';world=E.generate(seed,{systemCount:+$('#systemCount').value,factionCount:+$('#factionCount').value,temperament:$('#temperament').value});$('#seedInput').value=seed;selectedSystem=selectedFaction=null;timelineCutoff=0;fit();$('#newUniverseModal').classList.add('hidden');refreshAll();toast('A new timeline begins.')} ;$$('#interventionDock [data-action]').forEach(b=>b.onclick=()=>{const r=E.intervene(world,b.dataset.action,selectedFaction,selectedSystem);toast(r.message);refreshAll()});
canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height;zoom(e.deltaY<0?1.12:.89,x,y)},{passive:false});canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,ox:cam.ox,oy:cam.oy,moved:false};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>4)drag.moved=true;const r=canvas.getBoundingClientRect();cam.ox=drag.ox+dx*canvas.width/r.width;cam.oy=drag.oy+dy*canvas.height/r.height});canvas.addEventListener('pointerup',e=>{if(drag&&!drag.moved){const s=findSystemAt(e.clientX,e.clientY);if(s){selectedSystem=s.id;selectedFaction=s.owner;renderFocus();draw()}}drag=null});}
boot();
})();
