(()=>{
const COLORS=['#66d9ff','#ff6b6b','#ffd166','#8cff98','#b692ff','#ff8bd1','#66f0d0','#ff9f43','#8fb7ff','#e7ff6a','#ff7675','#74b9ff','#a29bfe','#55efc4'];
const GOV=[['Democratic Union',1.2,.8,1.2],['Stellar Republic',1.15,.9,1.1],['Imperial Dominion',.8,1.35,.9],['Technocratic Directorate',1,.85,1.05],['Merchant Compact',1.1,.7,1.4],['Military Junta',.7,1.55,.8],['Collective Assembly',1.05,.95,1.05],['Sacred Hierarchy',.85,1.1,.9],['Corporate Authority',.95,.85,1.35],['Nomadic Confederacy',1.05,1.05,1.15]];
const PRE=['Astra','Veyra','Orion','Khar','Sol','Nova','Elys','Drav','Cygn','Tauri','Helio','Zerin','Mira','Vanta','Aurel','Nex','Vel','Ilyr','Sable','Arc'];
const SUF=['ian','ari','on','ite','ean','ic','or','esh','ene','ax','um','is','eth','ora','id',' Reach',' Ascendancy'];
const SA=['Aster','Cinder','Helios','Nadir','Erebus','Lyra','Vega','Caelum','Arcturus','Mira','Khepri','Nyx','Talos','Icarus','Rhea','Astra','Vesper','Orpheus','Zenith','Umbra','Lumen','Atlas','Eos','Thalassa'];
const SB=['Prime','Secundus','Reach','Gate','Haven','Crown','Bastion','Drift','Crossing','Terminus','Spire','Delta','Nexus','Station','Vale','Expanse','Rift','March','Anchor','Watch'];
const TRAITS=['Expansionist','Diplomatic','Mercantile','Militarist','Scientific','Isolationist','Spiritual','Adaptive','Industrial','Exploratory'];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), key=(a,b)=>a<b?`${a}|${b}`:`${b}|${a}`, d=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function seeded(seed){let s=hash(seed)||1;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
const pick=(r,a)=>a[Math.floor(r()*a.length)];
function sys(w,id){return w.systems.filter(s=>s.owner===id)} function faction(w,id){return w.factions.find(f=>f.id===id)} function alive(w){return w.factions.filter(f=>f.alive)}
function rel(w,a,b){return w.relations[key(a,b)]??0} function setRel(w,a,b,v){w.relations[key(a,b)]=clamp(v,-100,100)} function adj(w,a,b,v){setRel(w,a,b,rel(w,a,b)+v)}
function atWar(w,a,b){return w.wars.some(x=>x.active&&((x.a===a&&x.b===b)||(x.a===b&&x.b===a)))} function allied(w,a,b){return w.alliances.some(x=>x.active&&x.members.includes(a)&&x.members.includes(b))}
function border(w,a,b){return sys(w,a).some(s=>s.neighbors.some(n=>w.systems[n]?.owner===b))}
function strength(w,id){const f=faction(w,id);return f?sys(w,id).reduce((z,s)=>z+s.population*.4+s.economy*.35+s.defense*.8,0)+f.fleet+f.tech*20:0}
function rand(w){w.rngState=(Math.imul(w.rngState||1,1664525)+1013904223)>>>0;return w.rngState/4294967296} const wp=(w,a)=>a[Math.floor(rand(w)*a.length)];
function evt(w,type,title,text,importance=1,actors=[]){w.events.unshift({id:++w.eventSeq,year:w.year,month:w.month,stamp:`${w.year}.${String(w.month).padStart(2,'0')}`,type,title,text,importance,actors:[...new Set(actors)]});if(w.events.length>800)w.events.length=800}
function name(r,used){let n;do n=pick(r,PRE)+pick(r,SUF);while(used.has(n));used.add(n);return n} function sname(r,used){let n;do n=`${pick(r,SA)} ${pick(r,SB)}`;while(used.has(n));used.add(n);return n}
function generate(seed='SOL-2200',o={}){const r=seeded(seed),count=+o.systemCount||180,nf=+o.factionCount||10,w={version:1,seed:String(seed),settings:{systemCount:count,factionCount:nf,temperament:o.temperament||'balanced'},year:2200,month:1,tick:0,eventSeq:0,rngState:Math.floor(r()*1e9),systems:[],factions:[],relations:{},wars:[],alliances:[],tradeRoutes:[],events:[],statsHistory:[]},sn=new Set();
for(let i=0;i<count;i++){const arm=i%4,rad=Math.sqrt(r())*.46+.03,ang=arm*Math.PI/2+rad*11+r()*.7;w.systems.push({id:i,name:sname(r,sn),x:clamp(.5+Math.cos(ang)*rad+(r()-.5)*.045,.035,.965),y:clamp(.5+Math.sin(ang)*rad*.72+(r()-.5)*.045,.05,.95),star:pick(r,['G','K','M','F','A','B']),habitability:Math.round(15+r()*85),resources:Math.round(15+r()*85),owner:null,population:0,economy:0,defense:0,unrest:0,development:0,capital:false,colonizedAt:null,neighbors:[]})}
for(const s of w.systems)s.neighbors=w.systems.filter(x=>x.id!==s.id).map(x=>[x.id,d(s,x)]).sort((a,b)=>a[1]-b[1]).slice(0,4).map(x=>x[0]);for(const s of w.systems)for(const n of s.neighbors)if(!w.systems[n].neighbors.includes(s.id)&&d(s,w.systems[n])<.13)w.systems[n].neighbors.push(s.id);
const fn=new Set(),caps=[];for(let i=0;i<nf;i++){let c=w.systems.filter(s=>caps.every(x=>d(s,x)>.17));if(!c.length)c=w.systems.filter(s=>!caps.includes(s));const cap=pick(r,c),[government,dip,war,trade]=pick(r,GOV),nm=name(r,fn),f={id:i,name:nm,short:nm.split(' ')[0],color:COLORS[i%COLORS.length],government,trait:pick(r,TRAITS),mods:{dip,war,trade},alive:true,capital:cap.id,treasury:90+r()*90,fleet:35+r()*35,tech:1+r()*.35,science:10+r()*25,stability:65+r()*22,warExhaustion:0,prestige:10+r()*20,born:2200,dead:null,warsWon:0,warsLost:0};w.factions.push(f);caps.push(cap);Object.assign(cap,{owner:i,capital:true,population:4+r()*5,economy:55+r()*35,defense:30+r()*25,development:45+r()*30,colonizedAt:2200});for(const s of cap.neighbors.map(n=>w.systems[n]).filter(s=>s.owner===null).slice(0,r()<.55?2:1))Object.assign(s,{owner:i,population:.8+r()*1.3,economy:15+r()*15,defense:8+r()*8,development:12+r()*15,colonizedAt:2200});evt(w,'politics',`${nm} enters the galactic stage`,`${government} rule is established around ${cap.name}.`,2,[i])}
for(let a=0;a<nf;a++)for(let b=a+1;b<nf;b++)setRel(w,a,b,Math.round(-15+r()*45+(border(w,a,b)?-10:0)));snapshot(w);return w}
function temp(w,k){const m={calm:{war:.45,crisis:.5,dip:1.2},balanced:{war:1,crisis:1,dip:1},volatile:{war:1.6,crisis:1.4,dip:.9},chaos:{war:2.5,crisis:2.1,dip:.75}};return m[w.settings.temperament]?.[k]||1}
function step(w){w.tick++;if(++w.month>12){w.month=1;w.year++}economy(w);if(w.tick%2===0)expand(w);if(w.tick%3===0)diplomacy(w);if(w.tick%3===1)trade(w);if(w.tick%2===1)warTick(w);if(w.tick%4===0)science(w);if(w.tick%6===0)politics(w);if(w.tick%12===0){crisis(w);snapshot(w)}cleanup(w)} function advance(w,n=1){for(let i=0;i<n;i++)step(w);return w}
function economy(w){for(const s of w.systems){if(s.owner===null)continue;const f=faction(w,s.owner);if(!f?.alive)continue;s.population=Math.max(.05,s.population*(1+.002+s.habitability/120000));s.economy=clamp(s.economy+s.resources*.0025+s.population*.018-s.unrest*.0015,1,220);s.development=clamp(s.development+.02*f.tech,0,100);s.defense=clamp(s.defense+.015,0,100);s.unrest=clamp(s.unrest+(50-f.stability)*.002,0,100);f.treasury+=s.economy*.006*f.mods.trade}for(const f of alive(w)){const ss=sys(w,f.id);f.treasury-=f.fleet*.012+ss.length*.08;f.fleet=clamp(f.fleet+(f.treasury>10?.03:-.08)*Math.max(1,ss.length),3,600);f.stability=clamp(f.stability+(f.treasury<0?-.12:.02)-f.warExhaustion*.003,4,100)}}
function expand(w){for(const f of alive(w)){if(f.treasury<8||f.stability<18)continue;const front=[];for(const s of sys(w,f.id))for(const n of s.neighbors){const t=w.systems[n];if(t.owner===null&&!front.includes(t))front.push(t)}if(!front.length||rand(w)>.025*(f.trait==='Expansionist'?1.4:1))continue;front.sort((a,b)=>(b.habitability+b.resources*.5)-(a.habitability+a.resources*.5));const t=front[Math.floor(rand(w)*Math.min(4,front.length))];Object.assign(t,{owner:f.id,population:.15+rand(w)*.3,economy:5+rand(w)*8,defense:3+rand(w)*5,development:5+rand(w)*7,colonizedAt:w.year+w.month/12});f.treasury-=10;if(rand(w)<.2)evt(w,'politics',`${f.name} colonizes ${t.name}`,`Settlers establish a permanent presence in ${t.name}.`,1,[f.id])}}
function diplomacy(w){const fs=alive(w);for(let i=0;i<fs.length;i++)for(let j=i+1;j<fs.length;j++){const a=fs[i],b=fs[j];adj(w,a.id,b.id,(rand(w)-.5)*1.5*temp(w,'dip')+(allied(w,a.id,b.id)?.25:0)-(atWar(w,a.id,b.id)?1.4:0));const rr=rel(w,a.id,b.id);if(rr>72&&!allied(w,a.id,b.id)&&!atWar(w,a.id,b.id)&&rand(w)<.012*a.mods.dip*b.mods.dip){w.alliances.push({id:w.alliances.length,members:[a.id,b.id],name:`${a.short}–${b.short} Accord`,formed:w.year+w.month/12,active:true});evt(w,'diplomacy',`${a.name} and ${b.name} sign an alliance`,'A mutual-defense and trade accord reshapes the regional balance.',3,[a.id,b.id])}if(rr<-62&&border(w,a.id,b.id)&&!atWar(w,a.id,b.id)&&rand(w)<.018*((a.mods.war+b.mods.war)/2)*temp(w,'war'))startWar(w,a.id,b.id)}}
function startWar(w,a,b,forced=false){if(a===b||atWar(w,a,b))return;const A=faction(w,a),B=faction(w,b);if(!A?.alive||!B?.alive)return;for(const x of w.alliances.filter(x=>x.active&&x.members.includes(a)&&x.members.includes(b)))x.active=false;adj(w,a,b,-40);w.wars.push({id:w.wars.length,a,b,active:true,start:w.year+w.month/12,months:0,aScore:0,bScore:0,battles:0,conquests:0,reason:forced?'Observer provocation':wp(w,['Border dispute','Resource rivalry','Ideological conflict','Colonial incident'])});evt(w,'war',`${A.name} declares war on ${B.name}`,'Open warfare erupts along the frontier.',4,[a,b])}
function warTick(w){for(const x of w.wars.filter(x=>x.active)){x.months++;const A=faction(w,x.a),B=faction(w,x.b);if(!A?.alive||!B?.alive){x.active=false;continue}A.warExhaustion+=.18;B.warExhaustion+=.18;const fronts=[];for(const s of w.systems)if(s.owner===x.a||s.owner===x.b)for(const n of s.neighbors){const t=w.systems[n];if((s.owner===x.a&&t.owner===x.b)||(s.owner===x.b&&t.owner===x.a))fronts.push([s,t])}if(fronts.length&&rand(w)<.3){const [from,to]=wp(w,fronts),att=from.owner,def=to.owner,AF=faction(w,att),DF=faction(w,def),av=strength(w,att)*(0.75+rand(w)*.5),dv=strength(w,def)*(0.6+rand(w)*.5)+to.defense*5;x.battles++;if(av>dv*1.05){const old=to.owner;to.owner=att;to.capital=false;to.defense*=.45;to.economy*=.9;to.unrest=clamp(to.unrest+25,0,100);att===x.a?x.aScore+=12:x.bScore+=12;x.conquests++;evt(w,'war',`${AF.name} captures ${to.name}`,`${DF.name} forces retreat after a major fleet engagement.`,3,[att,old]);if(faction(w,old).capital===to.id)relocate(w,faction(w,old))}}if(x.months>18&&((A.warExhaustion+B.warExhaustion)>65||Math.abs(x.aScore-x.bScore)>28||rand(w)<.018))endWar(w,x)}}
function endWar(w,x,forced=false){if(!x.active)return;x.active=false;x.end=w.year+w.month/12;const A=faction(w,x.a),B=faction(w,x.b);if(!A||!B)return;const win=x.aScore===x.bScore?null:(x.aScore>x.bScore?A:B),lose=win?.id===A.id?B:A;if(win){win.warsWon++;lose.warsLost++;win.prestige+=8}A.warExhaustion*=.4;B.warExhaustion*=.4;adj(w,A.id,B.id,forced?15:6);evt(w,'diplomacy',win?`${win.name} claims victory over ${lose.name}`:`${A.name} and ${B.name} agree to peace`,forced?'An observer-imposed armistice halts hostilities.':`After ${x.months} months, the war ends by treaty.`,3,[A.id,B.id])}
function trade(w){w.tradeRoutes=w.tradeRoutes.filter(r=>faction(w,r.a)?.alive&&faction(w,r.b)?.alive&&!atWar(w,r.a,r.b));const fs=alive(w);for(let i=0;i<fs.length;i++)for(let j=i+1;j<fs.length;j++){const a=fs[i],b=fs[j],rr=rel(w,a.id,b.id);if(rr<15||atWar(w,a.id,b.id))continue;const vol=Math.max(0,(rr+35)/135)*a.mods.trade*b.mods.trade*(6+Math.min(sys(w,a.id).length,sys(w,b.id).length));let rt=w.tradeRoutes.find(r=>key(r.a,r.b)===key(a.id,b.id));if(rt)rt.volume=rt.volume*.85+vol*.15;else if(rand(w)<.06)w.tradeRoutes.push({id:w.tradeRoutes.length,a:a.id,b:b.id,volume:vol,started:w.year+w.month/12})}}
function science(w){for(const f of alive(w)){f.science+=sys(w,f.id).reduce((z,s)=>z+s.development,0)/Math.max(1,sys(w,f.id).length)*.002;if(f.science>100){f.science-=100;f.tech+=.12;evt(w,'science',`${f.name} achieves a technological breakthrough`,`Technology level rises to ${f.tech.toFixed(2)}.`,2,[f.id])}}}
function politics(w){for(const f of alive(w)){const ss=sys(w,f.id);if(ss.length>=4&&f.stability<28&&rand(w)<.05*temp(w,'crisis'))rebellion(w,f);if(f.treasury<-25&&rand(w)<.05){f.stability-=7;evt(w,'economy',`${f.name} debt crisis`,'Military upkeep and weak revenues trigger a fiscal emergency.',2,[f.id])}}}
function rebellion(w,p){const candidates=sys(w,p.id).filter(s=>!s.capital);if(candidates.length<2)return;const s=wp(w,candidates),id=w.factions.length,nm=`${s.name.split(' ')[0]} Free State`,[g,dip,war,trade]=wp(w,GOV),r={id,name:nm,short:nm.split(' ')[0],color:COLORS[id%COLORS.length],government:g,trait:'Revolutionary',mods:{dip,war,trade},alive:true,capital:s.id,treasury:25,fleet:Math.max(12,p.fleet*.2),tech:p.tech*.92,science:10,stability:50,warExhaustion:0,prestige:2,born:w.year+w.month/12,dead:null,warsWon:0,warsLost:0};w.factions.push(r);s.owner=id;s.capital=true;s.unrest=25;p.stability-=10;for(const f of alive(w))if(f.id!==id)setRel(w,id,f.id,-10+rand(w)*25);evt(w,'politics',`${nm} secedes from ${p.name}`,`${s.name} rebels and proclaims an independent state.`,4,[p.id,id]);startWar(w,p.id,id)}
function crisis(w){if(rand(w)>.07*temp(w,'crisis'))return;const s=wp(w,w.systems.filter(x=>x.owner!==null));if(!s)return;const f=faction(w,s.owner),k=wp(w,['storm','plague','crash','boom']);if(k==='storm'){s.economy*=.82;s.defense*=.9;evt(w,'crisis',`Solar storm devastates ${s.name}`,'A severe stellar event damages infrastructure.',2,[f.id])}if(k==='plague'){s.population*=.92;s.unrest+=12;f.stability-=4;evt(w,'crisis',`Epidemic spreads through ${s.name}`,'Population loss and unrest follow a fast-moving pathogen.',3,[f.id])}if(k==='crash'){f.treasury-=35;f.stability-=5;evt(w,'economy',`${f.name} market crash`,'A speculative collapse erases wealth across the faction.',2,[f.id])}if(k==='boom'){f.treasury+=45;s.economy+=15;evt(w,'economy',`${s.name} enters an economic boom`,'Trade and industry surge unexpectedly.',2,[f.id])}}
function relocate(w,f){const a=sys(w,f.id);if(!a.length){collapse(w,f);return}const s=[...a].sort((x,y)=>(y.population+y.economy*.1)-(x.population+x.economy*.1))[0];for(const x of a)x.capital=false;s.capital=true;f.capital=s.id;evt(w,'politics',`${f.name} relocates its capital`,`${s.name} becomes the new seat of government.`,3,[f.id])}
function collapse(w,f){if(!f.alive)return;f.alive=false;f.dead=w.year+w.month/12;for(const x of w.wars.filter(x=>x.active&&(x.a===f.id||x.b===f.id)))x.active=false;evt(w,'politics',`${f.name} ceases to exist`,'The civilization loses its final controlled system.',5,[f.id])}
function cleanup(w){for(const f of alive(w))if(!sys(w,f.id).length)collapse(w,f)} function summary(w){return{factions:alive(w).length,population:w.systems.reduce((z,s)=>z+s.population,0),wars:w.wars.filter(x=>x.active).length,trade:w.tradeRoutes.reduce((z,r)=>z+r.volume,0),economy:w.systems.reduce((z,s)=>z+s.economy,0),colonized:w.systems.filter(s=>s.owner!==null).length}} function snapshot(w){w.statsHistory.push({year:w.year,month:w.month,...summary(w)});if(w.statsHistory.length>240)w.statsHistory.shift()}
function era(w){const s=summary(w),o=s.colonized/w.systems.length;if(s.factions<=3&&w.year>2250)return['Age of Hegemony','Only a few great powers remain.'];if(s.wars>=Math.max(3,s.factions/3))return['Age of War','Multiple civilizations are locked in major conflicts.'];if(o>.82)return['Age of Crowded Stars','Most systems are claimed; rivalry replaces expansion.'];if(w.year>=2240)return['Age of Rivalry','Expanding borders meet and diplomacy becomes critical.'];return['Age of Expansion','Young civilizations race into unclaimed space.']}
function intervene(w,a,fid,sid){const f=faction(w,fid);if(!f?.alive)return{ok:false,message:'Select a living faction first.'};if(a==='prosperity'){f.treasury+=100;f.stability=clamp(f.stability+8,0,100);for(const s of sys(w,f.id))s.economy+=5;evt(w,'economy',`An unexplained golden age favors ${f.name}`,'Prosperity arrives with suspiciously perfect timing.',3,[f.id]);return{ok:true,message:`Prosperity granted to ${f.name}.`}}if(a==='technology'){f.tech+=.25;evt(w,'science',`${f.name} receives impossible knowledge`,'A sudden scientific leap has no historical explanation.',3,[f.id]);return{ok:true,message:`Technology gifted to ${f.name}.`}}if(a==='peace'){let n=0;for(const x of w.wars.filter(x=>x.active&&(x.a===f.id||x.b===f.id))){endWar(w,x,true);n++}return{ok:n>0,message:n?`Ended ${n} war${n===1?'':'s'}.`:'Faction is not at war.'}}if(a==='tension'){const r=[...alive(w)].filter(x=>x.id!==f.id).sort((x,y)=>rel(w,f.id,x.id)-rel(w,f.id,y.id))[0];if(!r)return{ok:false,message:'No rival exists.'};adj(w,f.id,r.id,-50);if(border(w,f.id,r.id)&&!atWar(w,f.id,r.id))startWar(w,f.id,r.id,true);return{ok:true,message:`Tension raised with ${r.name}.`}}if(a==='rebellion'){f.stability=18;rebellion(w,f);return{ok:true,message:`Rebellion encouraged inside ${f.name}.`}}if(a==='disaster'){const s=w.systems[sid]?.owner===f.id?w.systems[sid]:w.systems[f.capital];s.population*=.86;s.economy*=.68;s.unrest+=30;f.stability-=7;evt(w,'crisis',`Catastrophe strikes ${s.name}`,'A devastating and statistically improbable disaster cripples the system.',4,[f.id]);return{ok:true,message:`Disaster struck ${s.name}.`}}return{ok:false,message:'Unknown intervention.'}}
function serialize(w){return JSON.stringify(w)} function deserialize(x){const w=typeof x==='string'?JSON.parse(x):x;if(!w?.systems||!w?.factions)throw Error('Invalid universe save');return w}
window.UTEngine={generate,advance,stepMonth:step,summary,era,intervene,serialize,deserialize,ownerSystems:sys,getFaction:faction,aliveFactions:alive,relation:rel,allied,atWar,strength,startWar,endWar,pushEvent:evt,adjustRelation:adj,pairKey:key};
})();
