(() => {
  const GOVS = [
    ['Democratic Union', {diplomacy:1.18, trade:1.2, war:.82, stability:1.08}],
    ['Stellar Republic', {diplomacy:1.12, trade:1.12, war:.9, stability:1.06}],
    ['Imperial Dominion', {diplomacy:.82, trade:.88, war:1.28, stability:1.02}],
    ['Technocratic Directorate', {diplomacy:.96, trade:1.05, war:.92, science:1.3}],
    ['Merchant Compact', {diplomacy:1.1, trade:1.42, war:.72, economy:1.22}],
    ['Military Junta', {diplomacy:.7, trade:.82, war:1.52, military:1.22}],
    ['Collective Assembly', {diplomacy:1.04, trade:1.04, war:.94, growth:1.12}],
    ['Sacred Hierarchy', {diplomacy:.86, trade:.9, war:1.08, stability:1.16}],
    ['Corporate Authority', {diplomacy:.94, trade:1.34, war:.88, economy:1.28}],
    ['Nomadic Confederacy', {diplomacy:1.06, trade:1.16, war:1.02, expansion:1.24}]
  ];
  const PREFIX = ['Astra','Veyra','Orion','Khar','Sol','Nova','Elys','Drav','Cygn','Tauri','Helio','Zerin','Mira','Vanta','Aurel','Nex','Vel','Ilyr','Sable','Arc'];
  const SUFFIX = ['ian','ari','on','ite','an','ari','ean','ic','or','esh','ene','ax','um','is','eth','ora','id',' Prime',' Reach',' Ascendancy'];
  const SYSTEM_A = ['Aster','Cinder','Helios','Nadir','Erebus','Lyra','Vega','Caelum','Arcturus','Mira','Khepri','Nyx','Talos','Icarus','Rhea','Astra','Vesper','Orpheus','Zenith','Umbra','Lumen','Atlas','Eos','Thalassa'];
  const SYSTEM_B = ['Prime','Secundus','Reach','Gate','Haven','Crown','Bastion','Drift','Crossing','Terminus','Spire','Delta','Nexus','Station','Vale','Expanse','Rift','March','Anchor','Watch'];
  const COLORS = ['#66d9ff','#ff6b6b','#ffd166','#8cff98','#b692ff','#ff8bd1','#66f0d0','#ff9f43','#8fb7ff','#e7ff6a','#ff7675','#74b9ff','#a29bfe','#55efc4','#fdcb6e','#e17055'];
  const STAR_CLASSES = ['G','K','M','F','A','B'];
  const TRAITS = ['Expansionist','Diplomatic','Mercantile','Militarist','Scientific','Isolationist','Spiritual','Adaptive','Industrial','Exploratory'];
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const pairKey=(a,b)=>a<b?`${a}|${b}`:`${b}|${a}`;
  function hashSeed(str){let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
  function rngFrom(seed){let s=hashSeed(String(seed))||1;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
  const pick=(rng,a)=>a[Math.floor(rng()*a.length)];
  function roman(n){const vals=[[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']];let s='';for(const [v,c] of vals)while(n>=v){s+=c;n-=v}return s}
  function factionName(rng, used){let n;do{n=pick(rng,PREFIX)+pick(rng,SUFFIX)}while(used.has(n));used.add(n);return n}
  function systemName(rng,used,i){let n;do{n=`${pick(rng,SYSTEM_A)} ${rng()<.56?pick(rng,SYSTEM_B):roman(1+Math.floor(rng()*7))}`}while(used.has(n));used.add(n);return n||`System ${i+1}`}
  function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
  function ownerSystems(world,id){return world.systems.filter(s=>s.owner===id)}
  function getFaction(world,id){return world.factions.find(f=>f.id===id)}
  function aliveFactions(world){return world.factions.filter(f=>f.alive)}
  function relation(world,a,b){return world.relations[pairKey(a,b)]??0}
  function setRelation(world,a,b,v){world.relations[pairKey(a,b)]=clamp(v,-100,100)}
  function adjustRelation(world,a,b,d){setRelation(world,a,b,relation(world,a,b)+d)}
  function atWar(world,a,b){return world.wars.some(w=>w.active&&((w.a===a&&w.b===b)||(w.a===b&&w.b===a)))}
  function allied(world,a,b){return world.alliances.some(x=>x.active&&x.members.includes(a)&&x.members.includes(b))}
  function hasBorder(world,a,b){const aSys=ownerSystems(world,a);return aSys.some(s=>s.neighbors.some(id=>world.systems[id]?.owner===b))}
  function fStrength(world,f){const systems=ownerSystems(world,f.id);return systems.reduce((sum,s)=>sum+s.population*.34+s.economy*.38+s.defense*.8,0)+f.fleet+f.tech*18}
  function temperamentScale(world,key){const t=world.settings.temperament;const map={calm:{war:.42,crisis:.5,diplomacy:1.2},balanced:{war:1,crisis:1,diplomacy:1},volatile:{war:1.65,crisis:1.4,diplomacy:.88},chaos:{war:2.55,crisis:2.15,diplomacy:.72}};return map[t]?.[key]??1}
  function pushEvent(world,type,title,text,importance=1,actors=[]){const e={id:++world.eventSeq,year:world.year,month:world.month,type,title,text,importance,actors:[...new Set(actors)],stamp:`${world.year}.${String(world.month).padStart(2,'0')}`};world.events.unshift(e);if(world.events.length>900)world.events.length=900;return e}
  function generate(seed='SOL-2200', opts={}){
    const rng=rngFrom(seed);const count=+opts.systemCount||180;const factionCount=+opts.factionCount||10;const world={version:1,seed:String(seed),settings:{systemCount:count,factionCount,temperament:opts.temperament||'balanced'},year:2200,month:1,tick:0,eventSeq:0,systems:[],factions:[],relations:{},wars:[],alliances:[],tradeRoutes:[],events:[],statsHistory:[],rngState:Math.floor(rng()*1e9)};
    const usedNames=new Set();
    for(let i=0;i<count;i++){
      const arm=i%4;const radial=Math.sqrt(rng())*.46+.035;const angle=arm*Math.PI/2+radial*11+rng()*.65;const squash=.72;let x=.5+Math.cos(angle)*radial+(rng()-.5)*.045;let y=.5+Math.sin(angle)*radial*squash+(rng()-.5)*.045;
      x=clamp(x,.035,.965);y=clamp(y,.05,.95);
      const habit=clamp(Math.round(20+rng()*80+(rng()<.17?18:0)),5,100);const resources=clamp(Math.round(25+rng()*70+(rng()<.14?20:0)),5,100);
      world.systems.push({id:i,name:systemName(rng,usedNames,i),x,y,star:pick(rng,STAR_CLASSES),habitability:habit,resources,owner:null,population:0,economy:0,defense:0,unrest:0,development:0,colonizedAt:null,capital:false});
    }
    // nearest-neighbour hyperlane graph
    for(const s of world.systems){const near=world.systems.filter(o=>o.id!==s.id).map(o=>[o.id,dist(s,o)]).sort((a,b)=>a[1]-b[1]).slice(0,4+(rng()<.22?1:0));s.neighbors=near.map(x=>x[0])}
    for(const s of world.systems)for(const n of s.neighbors){if(!world.systems[n].neighbors.includes(s.id)&&dist(s,world.systems[n])<.14)world.systems[n].neighbors.push(s.id)}
    const usedF=new Set();const capitals=[];
    for(let i=0;i<factionCount;i++){
      let candidates=world.systems.filter(s=>capitals.every(c=>dist(s,c)>.18));if(!candidates.length)candidates=world.systems.filter(s=>!capitals.includes(s));const cap=pick(rng,candidates);capitals.push(cap);
      const [government,mods]=pick(rng,GOVS);const trait=pick(rng,TRAITS);const name=factionName(rng,usedF);const f={id:i,name,short:name.split(/\s/)[0],color:COLORS[i%COLORS.length],government,trait,mods:{...mods},alive:true,capital:cap.id,treasury:70+rng()*80,fleet:30+rng()*35,tech:1+rng()*.35,science:18+rng()*18,stability:62+rng()*25,warExhaustion:0,prestige:10+rng()*20,born:2200,dead:null,colonies:1,warsWon:0,warsLost:0};world.factions.push(f);
      cap.owner=i;cap.capital=true;cap.population=4.5+rng()*4.5;cap.economy=55+rng()*35;cap.defense=32+rng()*24;cap.development=45+rng()*30;cap.colonizedAt=2200;
      // seed 1-2 nearby colonies
      const nearby=cap.neighbors.map(id=>world.systems[id]).filter(s=>s.owner===null).sort((a,b)=>b.habitability-a.habitability);
      for(const s of nearby.slice(0,rng()<.55?2:1)){s.owner=i;s.population=.8+rng()*1.5;s.economy=16+rng()*18;s.defense=8+rng()*9;s.development=12+rng()*18;s.colonizedAt=2200;f.colonies++}
      pushEvent(world,'politics',`${name} enters the galactic stage`,`${government} rule is established around ${cap.name}.`,2,[i]);
    }
    for(let a=0;a<factionCount;a++)for(let b=a+1;b<factionCount;b++){const proximity=hasBorder(world,a,b)?-10:0;setRelation(world,a,b,Math.round(-15+rng()*45+proximity))}
    snapshotStats(world);return world;
  }
  function localRng(world){world.rngState=(Math.imul(world.rngState||1,1664525)+1013904223)>>>0;return world.rngState/4294967296}
  const wrand=world=>localRng(world);
  const wpick=(world,a)=>a[Math.floor(wrand(world)*a.length)];
  function advance(world,months=1){for(let i=0;i<months;i++)stepMonth(world);return world}
  function stepMonth(world){world.tick++;world.month++;if(world.month>12){world.month=1;world.year++;yearly(world)}
    economyAndPopulation(world);if(world.tick%3===0)diplomacy(world);if(world.tick%2===0)expansion(world);if(world.tick%3===1)trade(world);if(world.tick%2===1)warTick(world);if(world.tick%6===0)politicalTick(world);if(world.tick%4===0)scienceTick(world);if(world.tick%12===0)crisisTick(world);if(world.tick%6===0)cleanup(world);if(world.tick%12===0)snapshotStats(world)
  }
  function economyAndPopulation(world){
    for(const s of world.systems){if(s.owner===null)continue;const f=getFaction(world,s.owner);if(!f?.alive)continue;const growth=(.0018+s.habitability/100000)*(f.mods.growth||1)*(1-s.unrest/150);s.population=Math.max(.05,s.population*(1+growth));const econGain=(s.resources*.003+s.population*.018)*(f.mods.economy||1);s.economy=clamp(s.economy+econGain-s.unrest*.0015,1,220);s.development=clamp(s.development+.018*(f.tech||1),0,100);s.defense=clamp(s.defense+.012*s.economy/20,0,100);s.unrest=clamp(s.unrest+(50-f.stability)*.002-(f.stability-60)*.001,0,100);f.treasury+=s.economy*.007*(f.mods.trade||1)}
    for(const f of aliveFactions(world)){const ss=ownerSystems(world,f.id);const upkeep=f.fleet*.014+ss.length*.09;f.treasury-=upkeep;f.fleet=clamp(f.fleet+(f.treasury>15?.02:-.08)*Math.max(1,ss.length),3,600);f.stability=clamp(f.stability+(f.treasury<0?-.12:.025)-f.warExhaustion*.003,4,100);f.treasury=clamp(f.treasury,-80,5000);if(f.treasury<-35&&wrand(world)<.025){pushEvent(world,'economy',`${f.name} debt crisis`,`Military upkeep and weak revenues have pushed the ${f.government.toLowerCase()} into a severe fiscal crisis.`,2,[f.id]);f.stability-=7}}
  }
  function expansion(world){
    for(const f of aliveFactions(world)){if(f.treasury<8||f.stability<18)continue;const owned=ownerSystems(world,f.id);const frontier=[];for(const s of owned)for(const n of s.neighbors){const t=world.systems[n];if(t.owner===null&&!frontier.includes(t))frontier.push(t)}if(!frontier.length)continue;const expansionMod=(f.mods.expansion||1)*(f.trait==='Expansionist'?1.35:1);const chance=.025*expansionMod*Math.min(2,1+f.treasury/400);if(wrand(world)>chance)continue;frontier.sort((a,b)=>(b.habitability+b.resources*.5)-(a.habitability+a.resources*.5));const target=frontier[Math.floor(wrand(world)*Math.min(4,frontier.length))];target.owner=f.id;target.population=.12+wrand(world)*.35;target.economy=5+wrand(world)*8;target.defense=3+wrand(world)*5;target.development=5+wrand(world)*6;target.colonizedAt=world.year+world.month/12;f.treasury-=10;f.colonies++;if(wrand(world)<.18)pushEvent(world,'politics',`${f.name} colonizes ${target.name}`,`Settlers establish a permanent presence in the ${target.name} system.`,1,[f.id])}
  }
  function diplomacy(world){
    const fs=aliveFactions(world);for(let i=0;i<fs.length;i++)for(let j=i+1;j<fs.length;j++){const a=fs[i],b=fs[j];let drift=(wrand(world)-.5)*1.6*temperamentScale(world,'diplomacy');if(a.trait==='Diplomatic'||b.trait==='Diplomatic')drift+=.25;if(a.trait==='Isolationist'||b.trait==='Isolationist')drift-=.18;if(atWar(world,a.id,b.id))drift-=1.6;else if(allied(world,a.id,b.id))drift+=.35;adjustRelation(world,a.id,b.id,drift);
      const rel=relation(world,a.id,b.id);if(!atWar(world,a.id,b.id)&&!allied(world,a.id,b.id)&&rel>72&&wrand(world)<.012*(a.mods.diplomacy||1)*(b.mods.diplomacy||1)){createAlliance(world,a.id,b.id)}
      if(allied(world,a.id,b.id)&&rel<15&&wrand(world)<.03){breakAlliance(world,a.id,b.id)}
      if(!atWar(world,a.id,b.id)&&hasBorder(world,a.id,b.id)&&rel<-62){const warBias=((a.mods.war||1)+(b.mods.war||1))/2*temperamentScale(world,'war');if(wrand(world)<.018*warBias)startWar(world,a.id,b.id)}
    }
  }
  function createAlliance(world,a,b){const existing=world.alliances.find(x=>x.active&&x.members.includes(a)&&x.members.includes(b));if(existing)return;const A=getFaction(world,a),B=getFaction(world,b);world.alliances.push({id:world.alliances.length,a,b,members:[a,b],name:`${A.short}–${B.short} Accord`,formed:world.year+world.month/12,active:true});adjustRelation(world,a,b,12);pushEvent(world,'diplomacy',`${A.name} and ${B.name} sign an alliance`,`The ${A.short}–${B.short} Accord pledges mutual defense and closer strategic cooperation.`,3,[a,b])}
  function breakAlliance(world,a,b){const x=world.alliances.find(x=>x.active&&x.members.includes(a)&&x.members.includes(b));if(!x)return;x.active=false;x.ended=world.year+world.month/12;const A=getFaction(world,a),B=getFaction(world,b);pushEvent(world,'diplomacy',`${x.name} collapses`,`${A.name} and ${B.name} formally abandon their alliance.`,2,[a,b])}
  function startWar(world,a,b,forced=false){if(a===b||atWar(world,a,b))return null;const A=getFaction(world,a),B=getFaction(world,b);if(!A?.alive||!B?.alive)return null;for(const x of world.alliances.filter(x=>x.active)){if(x.members.includes(a)&&x.members.includes(b))x.active=false}adjustRelation(world,a,b,-40);const w={id:world.wars.length,a,b,active:true,start:world.year+world.month/12,startYear:world.year,months:0,aScore:0,bScore:0,battles:0,conquests:0,reason:forced?'Observer-provoked conflict':wpick(world,['Border dispute','Resource rivalry','Ideological conflict','Strategic containment','Colonial incident'])};world.wars.push(w);pushEvent(world,'war',`${A.name} declares war on ${B.name}`,`${w.reason} ignites open warfare across the frontier.`,4,[a,b]);return w}
  function warTick(world){for(const w of world.wars.filter(w=>w.active)){w.months++;const A=getFaction(world,w.a),B=getFaction(world,w.b);if(!A?.alive||!B?.alive){endWar(world,w);continue}A.warExhaustion=clamp(A.warExhaustion+.18,0,100);B.warExhaustion=clamp(B.warExhaustion+.18,0,100);A.treasury-=.45;B.treasury-=.45;
      const borders=[];for(const s of world.systems){if(s.owner!==w.a&&s.owner!==w.b)continue;for(const n of s.neighbors){const t=world.systems[n];if((s.owner===w.a&&t.owner===w.b)||(s.owner===w.b&&t.owner===w.a))borders.push([s,t])}}
      if(borders.length&&wrand(world)<.28){const [from,to]=wpick(world,borders),att=from.owner,def=to.owner;const AF=getFaction(world,att),DF=getFaction(world,def);const attack=fStrength(world,AF)*(0.75+wrand(world)*.5)*(AF.mods.military||1);const defense=fStrength(world,DF)*(0.58+wrand(world)*.52)+to.defense*6;w.battles++;AF.fleet=clamp(AF.fleet-(defense/Math.max(attack,1))*2.2,2,600);DF.fleet=clamp(DF.fleet-(attack/Math.max(defense,1))*2.4,2,600);if(attack>defense*1.06){const old=to.owner;to.owner=att;to.capital=false;to.defense*=.38;to.economy*=.88;to.population*=.97;to.unrest=clamp(to.unrest+26,0,100);w.conquests++;if(att===w.a)w.aScore+=12;else w.bScore+=12;pushEvent(world,'war',`${AF.name} captures ${to.name}`,`${to.name} falls after a major fleet engagement. ${DF.name} forces retreat from the system.`,3,[att,old]);if(getFaction(world,old).capital===to.id)relocateCapital(world,getFaction(world,old))}else{if(att===w.a)w.aScore-=2;else w.bScore-=2;if(wrand(world)<.12)pushEvent(world,'war',`Battle of ${to.name} repelled`,`${DF.name} defenses hold against an assault by ${AF.name}.`,2,[att,def])}}
      const exhaustion=(A.warExhaustion+B.warExhaustion)/2;const dominance=Math.abs(w.aScore-w.bScore);if(w.months>18&&(exhaustion>35||dominance>30||wrand(world)<.018)){endWar(world,w)}
    }}
  function endWar(world,w,forced=false){if(!w.active)return;w.active=false;w.end=world.year+world.month/12;const A=getFaction(world,w.a),B=getFaction(world,w.b);const winner=w.aScore===w.bScore?null:(w.aScore>w.bScore?A:B);const loser=winner?.id===A.id?B:A;if(winner){winner.warsWon++;loser.warsLost++;winner.prestige+=8;loser.prestige=Math.max(0,loser.prestige-5)}A.warExhaustion*=.45;B.warExhaustion*=.45;adjustRelation(world,A.id,B.id,forced?12:6);pushEvent(world,'diplomacy',winner?`${winner.name} claims victory over ${loser.name}`:`${A.name} and ${B.name} agree to peace`,forced?'An observer-imposed armistice halts hostilities.':winner?`After ${w.months} months of war, a treaty recognizes ${winner.name}'s battlefield advantage.`:`After ${w.months} months of inconclusive fighting, both sides accept a negotiated settlement.`,3,[A.id,B.id]);checkCollapse(world,A);checkCollapse(world,B)}
  function relocateCapital(world,f){const ss=ownerSystems(world,f.id);if(!ss.length){collapseFaction(world,f);return}const best=ss.sort((a,b)=>(b.population+b.economy*.08)-(a.population+a.economy*.08))[0];for(const s of ss)s.capital=false;best.capital=true;f.capital=best.id;pushEvent(world,'politics',`${f.name} relocates its capital`,`${best.name} becomes the new seat of government after the loss of the former capital.`,3,[f.id])}
  function trade(world){world.tradeRoutes=world.tradeRoutes.filter(r=>getFaction(world,r.a)?.alive&&getFaction(world,r.b)?.alive&&!atWar(world,r.a,r.b));const fs=aliveFactions(world);for(let i=0;i<fs.length;i++)for(let j=i+1;j<fs.length;j++){const a=fs[i],b=fs[j],rel=relation(world,a.id,b.id);if(rel<15||atWar(world,a.id,b.id))continue;const existing=world.tradeRoutes.find(r=>pairKey(r.a,r.b)===pairKey(a.id,b.id));const vol=Math.max(0,(rel+35)/135)*(a.mods.trade||1)*(b.mods.trade||1)*(6+Math.min(ownerSystems(world,a.id).length,ownerSystems(world,b.id).length)*1.4);if(existing)existing.volume=existing.volume*.86+vol*.14;else if(wrand(world)<.07)world.tradeRoutes.push({id:world.tradeRoutes.length,a:a.id,b:b.id,volume:vol,started:world.year+world.month/12});a.treasury+=vol*.012;b.treasury+=vol*.012}}
  function politicalTick(world){for(const f of aliveFactions(world)){const ss=ownerSystems(world,f.id);if(!ss.length){collapseFaction(world,f);continue}const avgUnrest=ss.reduce((a,s)=>a+s.unrest,0)/ss.length;if((f.stability<28||avgUnrest>58)&&ss.length>=4&&wrand(world)<.06*temperamentScale(world,'crisis'))triggerRebellion(world,f);if(f.stability<12&&wrand(world)<.04){f.stability+=15;const old=f.government,[gov,mods]=wpick(world,GOVS);f.government=gov;f.mods={...mods};pushEvent(world,'politics',`Regime change in ${f.name}`,`${old} rule collapses. A new ${gov.toLowerCase()} takes power amid prolonged instability.`,3,[f.id])}}}
  function triggerRebellion(world,parent){const ss=ownerSystems(world,parent.id).filter(s=>!s.capital);if(ss.length<2)return;const seed=wpick(world,ss.sort((a,b)=>b.unrest-a.unrest).slice(0,Math.min(4,ss.length)));const cluster=[seed];for(const n of seed.neighbors){const s=world.systems[n];if(s.owner===parent.id&&!s.capital&&wrand(world)<.38)cluster.push(s)}if(cluster.length<1)return;const used=new Set(world.factions.map(f=>f.name));const [gov,mods]=wpick(world,GOVS);const id=world.factions.length;const rebel={id,name:factionName(()=>wrand(world),used),short:'Rebels',color=COLORS[id%COLORS.length],government:gov,trait:wpick(world,TRAITS),mods:{...mods},alive:true,capital:seed.id,treasury:25,fleet:Math.max(12,parent.fleet*.22),tech:Math.max(1,parent.tech*.92),science:10,stability:48,warExhaustion:0,prestige:2,born:world.year+world.month/12,dead:null,colonies:cluster.length,warsWon:0,warsLost:0};
    // syntax workaround for object shorthand assignment
    rebel.color=COLORS[id%COLORS.length];world.factions.push(rebel);for(const s of cluster){s.owner=id;s.unrest=30;s.capital=s.id===seed.id}parent.fleet*=.82;parent.stability-=10;for(const other of aliveFactions(world)){if(other.id!==id)setRelation(world,id,other.id,-10+wrand(world)*30)}pushEvent(world,'politics',`${rebel.name} secedes from ${parent.name}`,`${cluster.length} system${cluster.length===1?'':'s'} revolt and proclaim an independent ${gov.toLowerCase()}.`,4,[parent.id,id]);startWar(world,parent.id,id)}
  function scienceTick(world){for(const f of aliveFactions(world)){const ss=ownerSystems(world,f.id);const gain=(ss.reduce((a,s)=>a+s.development,0)/Math.max(1,ss.length))*.002*(f.mods.science||1);f.science+=gain;if(f.science>100){f.science-=100;f.tech+=.12;f.prestige+=3;for(const s of ss){s.economy+=2;s.defense+=1}pushEvent(world,'science',`${f.name} achieves a technological breakthrough`,`Researchers advance the civilization to technology level ${f.tech.toFixed(2)}, improving industry and defense.`,2,[f.id])}}}
  function crisisTick(world){if(wrand(world)>.075*temperamentScale(world,'crisis'))return;const kinds=['solar','plague','market','piracy','boom'];const kind=wpick(world,kinds);const occupied=world.systems.filter(s=>s.owner!==null);if(!occupied.length)return;const s=wpick(world,occupied),f=getFaction(world,s.owner);if(kind==='solar'){s.economy*=.85;s.defense*=.88;s.population*=.985;pushEvent(world,'crisis',`Solar storm devastates ${s.name}`,`A severe stellar event disrupts infrastructure across the system.`,2,[f.id])}else if(kind==='plague'){s.population*=.92;s.unrest+=12;f.stability-=4;pushEvent(world,'crisis',`Epidemic spreads through ${s.name}`,`A fast-moving pathogen causes population loss and social disruption.`,3,[f.id])}else if(kind==='market'){f.treasury-=35;f.stability-=5;pushEvent(world,'economy',`${f.name} market crash`,`A speculative collapse erases wealth and strains the state treasury.`,2,[f.id])}else if(kind==='piracy'){f.treasury-=15;f.fleet-=4;pushEvent(world,'crisis',`Piracy surges near ${s.name}`,`Trade lanes become dangerous as organized raiders exploit weak patrols.`,1,[f.id])}else{f.treasury+=45;f.stability+=4;s.economy+=15;pushEvent(world,'economy',`${s.name} enters an economic boom`,`New industries and trade investment trigger exceptional growth.`,2,[f.id])}}
  function yearly(world){for(const f of aliveFactions(world)){f.prestige=clamp(f.prestige+(ownerSystems(world,f.id).length*.15)+(f.tech-1)*.8,0,1000)}if(world.year%25===0){const top=[...aliveFactions(world)].sort((a,b)=>fStrength(world,b)-fStrength(world,a))[0];if(top)pushEvent(world,'politics',`${top.name} dominates the year ${world.year}`,`With ${ownerSystems(world,top.id).length} systems and growing prestige, it is regarded as the leading galactic power.`,2,[top.id])}}
  function cleanup(world){for(const f of aliveFactions(world))checkCollapse(world,f);world.tradeRoutes=world.tradeRoutes.filter(r=>getFaction(world,r.a)?.alive&&getFaction(world,r.b)?.alive)}
  function checkCollapse(world,f){if(f.alive&&!ownerSystems(world,f.id).length)collapseFaction(world,f)}
  function collapseFaction(world,f){if(!f.alive)return;f.alive=false;f.dead=world.year+world.month/12;for(const w of world.wars.filter(w=>w.active&&(w.a===f.id||w.b===f.id)))w.active=false;for(const a of world.alliances.filter(a=>a.active&&a.members.includes(f.id)))a.active=false;pushEvent(world,'politics',`${f.name} ceases to exist`,`The civilization loses its final controlled star system and disappears as an independent galactic power.`,5,[f.id])}
  function snapshotStats(world){const fs=aliveFactions(world),pop=world.systems.reduce((a,s)=>a+s.population,0),econ=world.systems.reduce((a,s)=>a+s.economy,0);world.statsHistory.push({year:world.year,month:world.month,factions:fs.length,population:pop,economy:econ,wars:world.wars.filter(w=>w.active).length,trade:world.tradeRoutes.reduce((a,r)=>a+r.volume,0)});if(world.statsHistory.length>240)world.statsHistory.shift()}
  function era(world){const alive=aliveFactions(world).length,systemsOwned=world.systems.filter(s=>s.owner!==null).length/world.systems.length,wars=world.wars.filter(w=>w.active).length;if(alive<=3&&world.year>2250)return['Age of Hegemony','Only a few great powers remain, and the fate of the galaxy is concentrated in their hands.'];if(wars>=Math.max(3,alive/3))return['Age of War','Multiple civilizations are locked in major conflicts across the galaxy.'];if(systemsOwned>.82)return['Age of Crowded Stars','Most habitable systems are claimed. Expansion gives way to rivalry, diplomacy and internal politics.'];if(world.year>=2300)return['Mature Galactic Order','Old powers, dense trade networks and long memories define interstellar politics.'];if(world.year>=2240)return['Age of Rivalry','Expanding borders meet, and diplomacy becomes as important as colonization.'];return['Age of Expansion','Young civilizations reach beyond their home systems and race into unclaimed space.']}
  function intervene(world,action,targetFactionId,targetSystemId){const f=getFaction(world,targetFactionId);const s=world.systems[targetSystemId];if(!f?.alive)return {ok:false,message:'Select a living faction first.'};if(action==='prosperity'){f.treasury+=100;f.stability=clamp(f.stability+8,0,100);for(const x of ownerSystems(world,f.id))x.economy+=5;pushEvent(world,'economy',`An unexplained golden age favors ${f.name}`,`Investment, confidence and productivity surge with suspiciously perfect timing.`,3,[f.id]);return{ok:true,message:`Prosperity granted to ${f.name}.`}}
    if(action==='technology'){f.tech+=.25;f.science=Math.max(0,f.science-20);pushEvent(world,'science',`${f.name} receives impossible knowledge`,`A sudden leap in scientific capability has no clear historical explanation.`,3,[f.id]);return{ok:true,message:`Technology gifted to ${f.name}.`}}
    if(action==='peace'){let count=0;for(const w of world.wars.filter(w=>w.active&&(w.a===f.id||w.b===f.id))){endWar(world,w,true);count++}return{ok:count>0,message:count?`Forced peace ended ${count} war${count===1?'':'s'}.`:`${f.name} is not currently at war.`}}
    if(action==='tension'){const candidates=aliveFactions(world).filter(o=>o.id!==f.id).sort((a,b)=>relation(world,f.id,a.id)-relation(world,f.id,b.id));if(!candidates.length)return{ok:false,message:'No rival exists.'};const rival=candidates[0];adjustRelation(world,f.id,rival.id,-50);if(!atWar(world,f.id,rival.id)&&hasBorder(world,f.id,rival.id))startWar(world,f.id,rival.id,true);else pushEvent(world,'diplomacy',`Tensions spike between ${f.name} and ${rival.name}`,`Diplomatic relations deteriorate after a chain of unexplained provocations.`,3,[f.id,rival.id]);return{ok:true,message:`Tension raised with ${rival.name}.`}}
    if(action==='rebellion'){if(ownerSystems(world,f.id).length<4)return{ok:false,message:'Faction needs at least four systems for a meaningful rebellion.'};f.stability=Math.min(f.stability,20);for(const x of ownerSystems(world,f.id).filter(x=>!x.capital))x.unrest=clamp(x.unrest+35,0,100);triggerRebellion(world,f);return{ok:true,message:`Unrest ignited inside ${f.name}.`}}
    if(action==='disaster'){const target=s?.owner===f.id?s:world.systems[f.capital];target.population*=.86;target.economy*=.68;target.defense*=.7;target.unrest=clamp(target.unrest+32,0,100);f.stability-=7;pushEvent(world,'crisis',`Catastrophe strikes ${target.name}`,`A devastating and statistically improbable disaster kills millions and cripples infrastructure.`,4,[f.id]);return{ok:true,message:`Disaster struck ${target.name}.`}}
    return{ok:false,message:'Unknown intervention.'}}
  function summary(world){const fs=aliveFactions(world),wars=world.wars.filter(w=>w.active),pop=world.systems.reduce((a,s)=>a+s.population,0),trade=world.tradeRoutes.reduce((a,r)=>a+r.volume,0),econ=world.systems.reduce((a,s)=>a+s.economy,0);return{factions:fs.length,population:pop,wars:wars.length,trade,economy:econ,colonized:world.systems.filter(s=>s.owner!==null).length}}
  function strength(world,id){const f=getFaction(world,id);return f?fStrength(world,f):0}
  function serialize(world){return JSON.stringify(world)}
  function deserialize(text){const w=typeof text==='string'?JSON.parse(text):text;if(!w||!Array.isArray(w.systems)||!Array.isArray(w.factions))throw new Error('Invalid universe save');return w}
  window.UTEngine={generate,advance,stepMonth,summary,era,intervene,serialize,deserialize,ownerSystems,getFaction,aliveFactions,relation,allied,atWar,strength,pairKey,startWar,endWar,pushEvent,adjustRelation};
})();
