(()=>{
const E=window.UTEngine;if(!E||E.__deepExpansion)return;E.__deepExpansion=true;
const oldGenerate=E.generate,oldStep=E.stepMonth,oldDeserialize=E.deserialize;
const IDEOLOGIES=['Cosmopolitan Liberalism','Imperial Traditionalism','Technocratic Rationalism','Collectivist Solidarity','Mercantile Pragmatism','Militant Nationalism','Ecological Harmonism','Transhuman Ascension'];
const FAITHS=['The Luminous Path','Void Ancestor Cult','Celestial Covenant','Machine Communion','Solar Mysticism','The Quiet Doctrine','No State Faith'];
const LEADER_TRAITS=['Visionary','Cautious','Charismatic','Ruthless','Scholar','Reformer','Traditionalist','Strategist','Merchant Prince','Mystic'];
const LN1=['Aren','Kael','Mira','Sel','Vey','Tarin','Lyra','Orin','Nara','Cass','Ilya','Rhea','Dax','Aurel','Nyra','Zev','Thane','Elia','Korin','Sora'];
const LN2=['Valen','Toras','Merid','Kesh','Aster','Rhal','Voss','Ilyan','Seren','Drake','Cyr','Nova','Tallis','Vor','Eris','Maren','Sol','Kade','Avar','Zen'];
const MEGAS=[
 {type:'Dyson Swarm',cost:420,tech:2.05,bonus:'economy',desc:'A stellar-scale energy harvesting lattice.'},
 {type:'Gate Nexus',cost:360,tech:1.85,bonus:'trade',desc:'A transit megahub linking distant trade corridors.'},
 {type:'Ring Habitat',cost:390,tech:1.95,bonus:'population',desc:'A colossal artificial habitat around a strategic star.'},
 {type:'Grand Archive',cost:320,tech:1.75,bonus:'science',desc:'A civilization-scale repository of knowledge.'},
 {type:'Citadel Array',cost:350,tech:1.8,bonus:'fleet',desc:'A distributed bastion network protecting core space.'}
];
const RESOLUTIONS=[
 {name:'Galactic Research Charter',kind:'science',desc:'Member states pool scientific data and standardize research exchange.'},
 {name:'Free Trade Compact',kind:'trade',desc:'Tariffs are reduced across senate-recognized trade corridors.'},
 {name:'Colonial Rights Convention',kind:'stability',desc:'Protections for frontier populations reduce unrest.'},
 {name:'Mutual Crisis Fund',kind:'treasury',desc:'A shared emergency reserve is established for systemic shocks.'},
 {name:'Demilitarized Frontier Act',kind:'peace',desc:'Border escalation is discouraged through inspection and arbitration.'}
];
const CRISES=[
 {name:'The Null Swarm',kind:'swarm',desc:'Self-replicating void organisms consume infrastructure and biospheres.'},
 {name:'Machine Schism',kind:'machine',desc:'Autonomous war networks abandon their creators and coordinate across the galaxy.'},
 {name:'Dimensional Breach',kind:'breach',desc:'Unstable tears in spacetime unleash destructive anomalies into inhabited systems.'}
];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const pair=(a,b)=>a<b?`${a}|${b}`:`${b}|${a}`;
function rnd(w){w.rngState=(Math.imul(w.rngState||1,1103515245)+12345)>>>0;return w.rngState/4294967296}
const pick=(w,a)=>a[Math.floor(rnd(w)*a.length)];
function evt(w,type,title,text,importance=2,actors=[]){w.events.unshift({id:++w.eventSeq,year:w.year,month:w.month,stamp:`${w.year}.${String(w.month).padStart(2,'0')}`,type,title,text,importance,actors:[...new Set(actors)]});if(w.events.length>1200)w.events.length=1200}
function alive(w){return w.factions.filter(f=>f.alive)}
function systems(w,id){return w.systems.filter(s=>s.owner===id)}
function relation(w,a,b){return w.relations[pair(a,b)]??0}
function setRelation(w,a,b,v){w.relations[pair(a,b)]=clamp(v,-100,100)}
function leaderName(w){return `${pick(w,LN1)} ${pick(w,LN2)}`}
function autocratic(f){return /Imperial|Hierarchy|Junta|Authority/i.test(f.government)}
function makeLeader(w,f,inheritDynasty=true){const old=f.leader;let dynasty=old?.dynasty||`${pick(w,LN2)} Dynasty`;if(!autocratic(f)||!inheritDynasty||rnd(w)<.22)dynasty=`${pick(w,LN2)} Line`;return{name:leaderName(w),age:34+Math.floor(rnd(w)*25),trait:pick(w,LEADER_TRAITS),since:w.year,dynasty:autocratic(f)?dynasty:null,termEnds:autocratic(f)?null:w.year+4+Math.floor(rnd(w)*4)}}
function ensureFactionCulture(w,f){if(!f.ideology)f.ideology=pick(w,IDEOLOGIES);if(!f.faith)f.faith=pick(w,FAITHS);if(!f.leader)f.leader=makeLeader(w,f,false);if(f.espionage==null)f.espionage=20+rnd(w)*45;if(f.influence==null)f.influence=10+f.prestige*.6+rnd(w)*12}
function ancientSites(w){const candidates=w.systems.filter(s=>s.owner==null).sort((a,b)=>(b.resources+b.habitability)-(a.resources+a.habitability));const count=Math.max(3,Math.min(7,Math.floor(w.systems.length/35)));return candidates.slice(0,count).map((s,i)=>({id:i,systemId:s.id,name:['Auralith Vault','Silent Crown','Oracular Ruins','Blackstar Reliquary','Eidolon Gate','Firstborn Observatory','Pale Engine'][i%7],discovered:false,claimedBy:null,artifact:null}));}
function init(w){if(w.expansion?.version===2){E.currentWorld=w;return w}for(const f of w.factions)ensureFactionCulture(w,f);w.expansion={version:2,senate:{founded:null,lastSession:null,resolutions:[],speaker:null},federations:[],espionage:{operations:[],intel:{}},megastructures:[],ancients:{sites:ancientSites(w),artifacts:[],awakenedFaction:null},crisis:null,crisesDefeated:0,replay:[],leaderHistory:[],cultureShifts:[]};captureReplay(w,true);E.currentWorld=w;return w}
function captureReplay(w,force=false){const ex=w.expansion;if(!force&&w.year%5!==0)return;const last=ex.replay[ex.replay.length-1];if(last&&last.year===w.year)return;const s=E.summary(w);ex.replay.push({year:w.year,month:w.month,owners:w.systems.map(x=>x.owner),factions:w.factions.map(f=>({id:f.id,name:f.name,color:f.color,alive:f.alive,systems:systems(w,f.id).length,fleet:+f.fleet.toFixed(1),tech:+f.tech.toFixed(2)})),population:+s.population.toFixed(2),economy:+s.economy.toFixed(1),wars:s.wars,trade:+s.trade.toFixed(1),senate:!!ex.senate.founded,crisis:ex.crisis?.active?ex.crisis.name:null});if(ex.replay.length>90)ex.replay.shift()}
function leaderTick(w){for(const f of alive(w)){ensureFactionCulture(w,f);f.leader.age++;const l=f.leader;const election=!autocratic(f)&&l.termEnds!=null&&w.year>=l.termEnds;const mortality=l.age>82?.25:l.age>72?.10:l.age>62?.035:.008;if(election||rnd(w)<mortality){w.expansion.leaderHistory.unshift({faction:f.id,name:l.name,dynasty:l.dynasty,from:l.since,to:w.year,reason:election?'election':'death/succession'});const next=makeLeader(w,f,true);f.leader=next;evt(w,'politics',election?`${f.name} elects ${next.name}`:`${f.name} enters a new succession`,election?`${next.name}, a ${next.trait.toLowerCase()} leader, wins the transfer of power.`:`${l.name} leaves office; ${next.name} assumes leadership${next.dynasty?` of the ${next.dynasty}`:''}.`,2,[f.id])}}
 if(w.expansion.leaderHistory.length>120)w.expansion.leaderHistory.length=120}
function cultureTick(w){for(const f of alive(w)){f.influence=clamp(f.influence+(f.prestige-20)*.02+(f.stability-50)*.01,0,200);if(f.stability<30&&rnd(w)<.08){const old=f.ideology,choices=IDEOLOGIES.filter(x=>x!==old);f.ideology=pick(w,choices);w.expansion.cultureShifts.unshift({year:w.year,faction:f.id,from:old,to:f.ideology});evt(w,'politics',`${f.name} undergoes an ideological realignment`,`${old} loses ground to ${f.ideology} amid domestic instability.`,2,[f.id])}if(rnd(w)<.018){const allies=alive(w).filter(o=>o.id!==f.id&&E.allied?.(w,f.id,o.id));if(allies.length){const model=pick(w,allies);if(model.faith!==f.faith&&rnd(w)<.35){const old=f.faith;f.faith=model.faith;evt(w,'politics',`${f.name} experiences a religious shift`,`${old} gives way to growing influence from ${f.faith}.`,1,[f.id,model.id])}}}}
 if(w.expansion.cultureShifts.length>80)w.expansion.cultureShifts.length=80}
function senateWeight(w,f){return Math.max(1,systems(w,f.id).length*2+f.prestige*.08+f.influence*.06)}
function resolutionBias(f,r){let b=.52;if(r.kind==='science'&&/Technocratic|Rationalism|Transhuman/.test(`${f.government} ${f.ideology}`))b+=.2;if(r.kind==='trade'&&/Merchant|Corporate|Mercantile/.test(`${f.government} ${f.ideology}`))b+=.22;if(r.kind==='peace'&&/Military|Militant|Imperial/.test(`${f.government} ${f.ideology}`))b-=.18;if(r.kind==='stability'&&/Collective|Democratic|Cosmopolitan/.test(`${f.government} ${f.ideology}`))b+=.12;return clamp(b,.15,.88)}
function applyResolution(w,r){const fs=alive(w);if(r.kind==='science')for(const f of fs){f.science+=5;f.tech+=.018}if(r.kind==='trade')for(const f of fs)f.treasury+=18;if(r.kind==='stability')for(const f of fs){f.stability=clamp(f.stability+4,0,100);for(const s of systems(w,f.id))s.unrest=clamp(s.unrest-8,0,100)}if(r.kind==='treasury')for(const f of fs)f.treasury+=25;if(r.kind==='peace')for(let i=0;i<fs.length;i++)for(let j=i+1;j<fs.length;j++)setRelation(w,fs[i].id,fs[j].id,relation(w,fs[i].id,fs[j].id)+4)}
function senateTick(w){const s=w.expansion.senate,fs=alive(w);if(!s.founded&&w.year>=2235&&fs.length>=4){s.founded=w.year;s.speaker=fs.slice().sort((a,b)=>senateWeight(w,b)-senateWeight(w,a))[0]?.id??null;evt(w,'diplomacy','The Galactic Senate is founded','Major powers establish a permanent forum for interstellar law, trade and crisis coordination.',4,fs.map(f=>f.id));return}if(!s.founded||w.year-s.founded<1)return;if(s.lastSession&&w.year-s.lastSession<4)return;s.lastSession=w.year;const base=RESOLUTIONS[s.resolutions.length%RESOLUTIONS.length],votes=[];let yes=0,no=0;for(const f of fs){const weight=senateWeight(w,f),support=rnd(w)<resolutionBias(f,base);votes.push({faction:f.id,weight:+weight.toFixed(1),support});support?yes+=weight:no+=weight}const passed=yes>=no;const record={year:w.year,name:base.name,kind:base.kind,desc:base.desc,passed,yes:+yes.toFixed(1),no:+no.toFixed(1),votes};s.resolutions.unshift(record);if(s.resolutions.length>40)s.resolutions.length=40;if(passed)applyResolution(w,base);s.speaker=fs.slice().sort((a,b)=>senateWeight(w,b)-senateWeight(w,a))[0]?.id??null;evt(w,'diplomacy',`${base.name} ${passed?'passes':'fails'} in the Galactic Senate`,passed?`${yes.toFixed(0)} weighted votes approve the resolution against ${no.toFixed(0)}.`:`The chamber rejects the proposal ${no.toFixed(0)} to ${yes.toFixed(0)}.`,3,fs.map(f=>f.id))}
function allianceComponents(w){const adj=new Map(alive(w).map(f=>[f.id,new Set()]));for(const a of w.alliances.filter(x=>x.active)){for(const x of a.members)for(const y of a.members)if(x!==y&&adj.has(x)&&adj.has(y))adj.get(x).add(y)}const seen=new Set(),out=[];for(const id of adj.keys()){if(seen.has(id))continue;const q=[id],c=[];seen.add(id);while(q.length){const x=q.pop();c.push(x);for(const y of adj.get(x))if(!seen.has(y)){seen.add(y);q.push(y)}}if(c.length>=3)out.push(c)}return out}
function federationTick(w){const ex=w.expansion;for(const fed of ex.federations.filter(f=>f.active)){const live=fed.members.filter(id=>E.getFaction(w,id)?.alive);fed.members=live;if(live.length<2){fed.active=false;fed.dissolved=w.year;continue}let relsum=0,pairs=0;for(let i=0;i<live.length;i++)for(let j=i+1;j<live.length;j++){relsum+=relation(w,live[i],live[j]);pairs++}fed.cohesion=clamp((pairs?relsum/pairs:0)+45,0,100);if(fed.cohesion<22&&rnd(w)<.18){fed.active=false;fed.dissolved=w.year;evt(w,'diplomacy',`${fed.name} dissolves`,'Internal disputes overwhelm the federation charter and member states reclaim full sovereignty.',3,live);continue}if(w.year-fed.lastElection>=8){fed.president=live.slice().sort((a,b)=>(E.getFaction(w,b)?.prestige||0)-(E.getFaction(w,a)?.prestige||0))[0];fed.lastElection=w.year;evt(w,'diplomacy',`${E.getFaction(w,fed.president)?.name} assumes the ${fed.name} presidency`,'A new federal presidency begins after a scheduled leadership rotation.',2,live)}}
 for(const comp of allianceComponents(w)){if(ex.federations.some(f=>f.active&&comp.every(id=>f.members.includes(id))))continue;let avg=0,p=0;for(let i=0;i<comp.length;i++)for(let j=i+1;j<comp.length;j++){avg+=relation(w,comp[i],comp[j]);p++}avg=p?avg/p:0;if(avg>58&&rnd(w)<.28){const names=comp.map(id=>E.getFaction(w,id)?.short||'State');const president=comp.slice().sort((a,b)=>(E.getFaction(w,b)?.prestige||0)-(E.getFaction(w,a)?.prestige||0))[0],fed={id:ex.federations.length,name:`${names[0]} Galactic Federation`,members:[...comp],formed:w.year,active:true,cohesion:clamp(avg+35,0,100),president,lastElection:w.year};ex.federations.push(fed);evt(w,'diplomacy',`${fed.name} is proclaimed`,`${comp.length} allied civilizations bind themselves into a permanent federal bloc.`,4,comp)}}}
function intelKey(a,b){return `${a}>${b}`}
function espionageTick(w){const ex=w.expansion,fs=alive(w);if(fs.length<2)return;const attempts=Math.max(1,Math.floor(fs.length/3));for(let n=0;n<attempts;n++){const a=pick(w,fs),targets=fs.filter(x=>x.id!==a.id);targets.sort((x,y)=>relation(w,a.id,x.id)-relation(w,a.id,y.id));const b=targets[Math.floor(rnd(w)*Math.min(4,targets.length))];if(!b)continue;const k=intelKey(a.id,b.id),intel=ex.espionage.intel[k]??20+rnd(w)*30,op=pick(w,['Steal Technology','Sabotage Industry','Disinformation','Treasury Heist','Map Networks']),success=rnd(w)<clamp(.35+a.espionage/160+intel/300-b.stability/300,.12,.82),detected=rnd(w)<.36;ex.espionage.intel[k]=clamp(intel+(success?8:2),0,100);if(success){if(op==='Steal Technology'){a.tech+=.025;b.science=Math.max(0,b.science-2)}else if(op==='Sabotage Industry'){const ss=systems(w,b.id);if(ss.length)pick(w,ss).economy*=.9}else if(op==='Disinformation')b.stability=clamp(b.stability-4,0,100);else if(op==='Treasury Heist'){const amt=Math.min(22,Math.max(5,b.treasury*.08));b.treasury-=amt;a.treasury+=amt}else a.espionage=clamp(a.espionage+3,0,100)}if(detected){setRelation(w,a.id,b.id,relation(w,a.id,b.id)-10);evt(w,'politics',`${b.name} exposes an espionage operation`,`${a.name} is implicated in a ${op.toLowerCase()} campaign${success?' that partially succeeded':' that failed'}.`,2,[a.id,b.id])}ex.espionage.operations.unshift({year:w.year,attacker:a.id,target:b.id,type:op,success,detected});}if(ex.espionage.operations.length>100)ex.espionage.operations.length=100}
function megaBonus(w,m){const f=E.getFaction(w,m.faction);if(!f)return;if(m.bonus==='economy')for(const s of systems(w,f.id))s.economy*=1.08;if(m.bonus==='trade')f.treasury+=120;if(m.bonus==='population'){const cap=w.systems[f.capital];if(cap)cap.population*=1.18}if(m.bonus==='science'){f.tech+=.18;f.science+=35}if(m.bonus==='fleet'){f.fleet*=1.22;for(const s of systems(w,f.id))s.defense=clamp(s.defense+12,0,100)}}
function megastructureTick(w){const ex=w.expansion;for(const m of ex.megastructures.filter(x=>x.status==='building')){const f=E.getFaction(w,m.faction);if(!f?.alive){m.status='abandoned';continue}const spend=Math.min(45,Math.max(10,f.treasury*.08));f.treasury-=spend;m.progress=clamp(m.progress+7+spend*.16+f.tech*1.5,0,100);if(m.progress>=100){m.status='complete';m.completed=w.year;megaBonus(w,m);evt(w,'science',`${f.name} completes the ${m.type}`,`${m.desc} The project becomes a permanent symbol of galactic-scale engineering.`,4,[f.id])}}
 for(const f of alive(w)){if(ex.megastructures.some(m=>m.faction===f.id&&m.status==='building'))continue;if(ex.megastructures.filter(m=>m.faction===f.id&&m.status==='complete').length>=3)continue;const choices=MEGAS.filter(m=>f.tech>=m.tech);if(!choices.length||f.treasury<330||rnd(w)>.055)continue;const spec=pick(w,choices),m={id:ex.megastructures.length,faction:f.id,systemId:f.capital,type:spec.type,bonus:spec.bonus,desc:spec.desc,started:w.year,completed:null,progress:4+rnd(w)*8,status:'building'};ex.megastructures.push(m);f.treasury-=80;evt(w,'science',`${f.name} begins construction of a ${m.type}`,m.desc,3,[f.id])}}
function awakenAncient(w,site){const ex=w.expansion;if(ex.ancients.awakenedFaction!=null)return;const id=Math.max(-1,...w.factions.map(f=>f.id))+1,s=w.systems[site.systemId];if(!s)return;const old=s.owner;if(old!=null){const alt=w.systems.filter(x=>x.owner==null).sort((a,b)=>b.resources-a.resources)[0];if(alt)site.systemId=alt.id}const home=w.systems[site.systemId],f={id,name:'Auralith Remnant',short:'Auralith',color:'#f5e6a8',government:'Ancient Custodian Order',trait:'Scientific',mods:{dip:.62,war:1.45,trade:.8},alive:true,capital:home.id,treasury:900,fleet:260,tech:3.4,science:120,stability:88,warExhaustion:0,prestige:170,born:w.year,dead:null,warsWon:0,warsLost:0,ideology:'Technocratic Rationalism',faith:'The Quiet Doctrine',espionage:88,influence:150,ancient:true};f.leader=makeLeader(w,f,false);f.leader.name='Archivist Sael';f.leader.age=137;w.factions.push(f);home.owner=id;home.capital=true;home.population=3.2;home.economy=150;home.defense=92;home.development=100;for(const o of alive(w))if(o.id!==id)setRelation(w,id,o.id,-10+rnd(w)*35);ex.ancients.awakenedFaction=id;evt(w,'crisis','An ancient civilization awakens',`The ${f.name} emerges from the ${site.name}, fielding technology centuries beyond the younger powers.`,5,[id])}
function ancientTick(w){const ex=w.expansion;for(const site of ex.ancients.sites){if(site.discovered)continue;const s=w.systems[site.systemId];if(s?.owner!=null&&rnd(w)<.28){site.discovered=true;site.claimedBy=s.owner;const artifacts=['Quantum Star Map','Gravitic Codex','Chronicle Shard','Dark-Matter Lattice','Precursor Genome Archive'];site.artifact=pick(w,artifacts);ex.ancients.artifacts.push({year:w.year,site:site.id,faction:s.owner,name:site.artifact});const f=E.getFaction(w,s.owner);if(f){f.tech+=.06;f.prestige+=12}evt(w,'science',`${f?.name||'Explorers'} uncover the ${site.name}`,`The site yields a ${site.artifact}, accelerating research into precursor technology.`,3,[s.owner])}}
 if(w.year>=2325&&ex.ancients.awakenedFaction==null&&rnd(w)<.045){const site=ex.ancients.sites.find(x=>x.discovered)||pick(w,ex.ancients.sites);if(site)awakenAncient(w,site)}}
function startCrisis(w){const spec=pick(w,CRISES),ex=w.expansion;ex.crisis={name:spec.name,kind:spec.kind,desc:spec.desc,active:true,started:w.year,months:0,threat:95,damage:0,resistance:0,phase:'Emergence'};evt(w,'crisis',`${spec.name} begins`,spec.desc,5,alive(w).map(f=>f.id))}
function crisisMonth(w){const c=w.expansion.crisis;if(!c?.active)return;c.months++;const fs=alive(w);const totalFleet=fs.reduce((z,f)=>z+f.fleet,0),federal=w.expansion.federations.filter(f=>f.active).reduce((z,f)=>z+f.cohesion,0);c.resistance=totalFleet/18+federal*.12+fs.reduce((z,f)=>z+f.tech*2,0);c.threat=clamp(c.threat+(c.kind==='swarm'?1.5:c.kind==='machine'?1.15:.9)-c.resistance*.006,0,260);if(c.months%3===0){const targets=w.systems.filter(s=>s.owner!=null);if(targets.length){const s=pick(w,targets),f=E.getFaction(w,s.owner),severity=clamp(c.threat/130,.2,1.6);s.economy=Math.max(1,s.economy*(1-.05*severity));s.population=Math.max(.03,s.population*(1-.018*severity));s.unrest=clamp(s.unrest+6*severity,0,100);s.defense=Math.max(0,s.defense-5*severity);c.damage+=severity*10;if(rnd(w)<.38)evt(w,'crisis',`${c.name} strikes ${s.name}`,`${f?.name||'Local'} infrastructure suffers major losses as the crisis spreads.`,3,[s.owner])}}if(c.months>18&&c.threat<18){c.active=false;c.defeated=w.year;c.phase='Defeated';w.expansion.crisesDefeated++;for(const f of fs){f.prestige+=18;f.stability=clamp(f.stability+5,0,100)}evt(w,'crisis',`${c.name} is defeated`,'A coordinated galactic counteroffensive finally breaks the existential threat.',5,fs.map(f=>f.id));return}if(c.months>72&&c.threat>180)c.phase='Cataclysm';else if(c.months>24)c.phase='Galactic War';}
function crisisYear(w){const ex=w.expansion;if(ex.crisis?.active)return;if(ex.crisis&&!ex.crisis.active)return;if((w.year>=2360&&rnd(w)<.085)||w.year>=2410)startCrisis(w)}
function yearTick(w){leaderTick(w);cultureTick(w);senateTick(w);federationTick(w);espionageTick(w);megastructureTick(w);ancientTick(w);crisisYear(w);captureReplay(w)}
function afterStep(w){init(w);crisisMonth(w);if(w.month===1)yearTick(w);E.currentWorld=w}
E.generate=function(seed,o){return init(oldGenerate(seed,o))};
E.deserialize=function(s){return init(oldDeserialize(s))};
E.stepMonth=function(w){oldStep(w);afterStep(w);return w};
E.advance=function(w,n=1){for(let i=0;i<n;i++)E.stepMonth(w);return w};
E.expansionSummary=function(w){init(w);const ex=w.expansion;return{senate:ex.senate,federations:ex.federations.filter(f=>f.active),espionage:ex.espionage,megastructures:ex.megastructures,ancients:ex.ancients,crisis:ex.crisis,replay:ex.replay,leaders:w.factions.filter(f=>f.alive).map(f=>({faction:f.id,leader:f.leader,ideology:f.ideology,faith:f.faith,influence:f.influence}))}};
E.captureReplay= w=>captureReplay(w,true);
})();